# Generated by Django 2.1.7 on 2019-02-25 16:23

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('class_files', '0002_section_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
