# Generated by Django 2.1.7 on 2019-02-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_files', '0003_file_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='dropbox_path',
        ),
    ]
