# Generated by Django 2.1.7 on 2019-02-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_files', '0004_auto_20190225_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date',
            new_name='upload_date',
        ),
    ]
